name: 🧪 Code checking

on:
  push:
    branches:
      - dev
      - main
      - changeset-release/main
  pull_request:
    branches:
      - dev
      - main
      - changeset-release/main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  linting:
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup environment
        uses: ./.github/actions/pnpm-setup

      - name: Run ESLint
        run: pnpm run lint
  vitest:
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup environment
        uses: ./.github/actions/pnpm-setup

      - name: Run Vitests
        run: pnpm run test
